PIN 입력 화면과 Wi-Fi 리스트 화면 작업
euphony-io/waple pull request #19
Opened 2022-07-27 14:23 UTC by Kimhaedam

1) PIN 입력 화면
- 안내 문구 출력 (Wi-Fi 사용 권한을 얻으려면 PIN 번호를 입력해주세요!)
- 번호 입력 받는 textfield
- 확인 버튼

2) Wi-Fi 리스트 화면
- 텍스트 (사용 가능한 Wi-Fi 목록)
- 누르면 각 와이파이와 연결되는 와이파이 정보 버튼
- 홈화면으로 돌아가는 버튼

이렇게 구상하고 만들어봤는데 아직 오류가 많아 고쳐야할 부분이 많을 것 같습니다...
문제 있는 부분에 대해 모두 commit 작성해두겠습니다!
오류로 인해 에뮬레이터로 앱 실행이 불가능한 문제가 있어서, UI 수정과 화면 구성 등은 일단 다른 파일에서 작업 중입니다! 

![image](https://user-images.githubusercontent.com/94813704/181271236-da55ee98-5b0b-44bc-8882-4c4020d2988b.png)

2022-07-27 16:04 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/Screen.kt
> +    object WifiListScreen : Screen("WifiListScreen", R.string.wifi_list)
각각 R.string.enter_PIN은 "PIN 번호 입력", R.string.wifi-list는 "WI-FI 목록"으로
app/src/main/res/values/strings.xml에 추가하였습니다.

2022-07-27 16:04 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +        fun TextFieldTest() {
PIN 번호를 입력받는 Textfield를 만드려고 시도했던 부분입니다만 오류가 납니다. 
함수 위치가 잘못된 것 같은데 .. 수정을 어떻게 하면 좋을지 의견 주시면 감사하겠습니다!

2022-07-27 16:04 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
이 textfield는 PIN번호를 입력받을 때만 사용하는 필드라 키보드가 숫자로 뜨는게 편할 것 같아 `keyboardoptions`를 사용했습니다.

2022-07-27 16:04 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +@Composable
`사용 가능한 Wi-Fi 목록`이라는 화면의 제목이 뜨고
아래 리스트에 사용 가능한 Wi-Fi 개수만큼 버튼을 만들어 버튼내에 `와플아이콘이미지`와 함께 `와이파이명`이 뜨도록 하려 했습니다.
만약 바로 연결/복사 중 선택하도록 한다면 버튼을 둘로 나눠 만들어야 할 것 같습니다.

2022-07-27 16:04 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +                    label = "PIN 번호",
만약 잘못된 PIN 입력시 다른 화면으로 이동하지 않고 `toast`나 `snackbar`를 이용해 팝업 메시지 형식으로 잘못된 PIN이라는 걸 알려주면 좋을 것 같은데 더 괜찮은 방법이 있을까요?

2022-07-28 05:32 UTC, zion830 requested changes
고생하셨습니다!
1. 지금 .gradle이랑 buildSrc 관련된 파일이 뭔가 많이 올라왔는데 이 파일들은 지워도 될거같습니다!
2. 전체적으로 문자열들을 string.xml로 이동시키면 좋을거같아요!

2022-07-28 05:32 UTC, zion830 commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +        fun TextFieldTest() {
어떤 오류인지 로그도 같이 적어주시면 좋을거같아요!

2022-07-28 05:32 UTC, zion830 commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
좋아요 :) !!

2022-07-28 05:32 UTC, zion830 commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +                    label = "PIN 번호",
viewModel에 입력된 pin 번호가 유효한지 아닌지 검증하는 함수를 만들어서, 
확인 버튼을 눌렀을 때 결과에 따라 화면을 이동하거나 토스트 메세지를 띄우도록 하면 될거같아요!

그리고 test 폴더에 그 pin 번호 검증 함수에 대한 유닛 테스트까지 작성하면 좋을거같네용

2022-07-28 05:32 UTC, zion830 commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +            onClick = { startScreenBtnClick(Screen.WifiListScreen) },
여기서 인자로 받은 startScreenBtnClick의 타입 Screen.WifiListScreen는 함수가 아니라 sealed class에 선언된 하위 클래스중 하나라 이렇게하면 화면 이동이 아마 안될거예요. 
이거 말고 navigator를 인자로 받거나, () -> Unit 으로 함수를 인자로 받아서 화면을 이동시켜야 해요.

2022-07-28 05:32 UTC, zion830 commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +            text = "확인"
문자열을 이렇게 직접 쓰는걸 하드코딩이라고 하는데, 
가급적 앱 UI단에서 사용할 문자열은 전부 string.xml 파일에 선언해두고 stringResource 함수로 불러오는 것이 좋아요!

1. 왜냐면 (저희 앱에 지금은 필요가 없지만) 앱이 다국어를 지원하게 될 경우 언어별로 xml 파일을 추가하면 되거든요
2. 그리고 '확인' 문자열이 여러 화면에서 사용되고, 언젠가 '확인'을 '입력 완료' 이런 문자열로 수정하고 싶을 경우에 지금은 하드코딩한 모든 "확인"을 찾아서 수정해야 하잖아요? string.xml에 선언해두면 여기서 한번만 수정하면 돼서 훨씬 편리해요

2022-07-28 09:27 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +                    label = "PIN 번호",
좋습니다! 유닛 테스트를 어느 부분에서 할 수 있을지 고민 중이었는데 pin 번호 부분에서 필요할 것 같네요 :)

2022-07-28 09:28 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +            onClick = { startScreenBtnClick(Screen.WifiListScreen) },
그렇군요... 이 부분이 정말 헷갈렸는데 감사합니다!

2022-07-28 09:30 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +            text = "확인"
네 모두 string.xml에 선언해두겠습니다.😀

2022-07-29 15:12 UTC, haan823 approved these changes

2022-07-29 18:03 UTC, closed without merging