Button name 수정 및 pin branch conflict 해결
euphony-io/waple pull request #28
Opened 2022-08-06 15:41 UTC by Kimhaedam

string.xml conflicts 해결이 필요해 보입니다.

2022-08-06 15:43 UTC, Kimhaedam commented
- string.xml conflicts 수정 완료
- 실수로 지운 buildSrc 내의 코틀린 파일 복구

2022-08-06 16:17 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/Screen.kt
> +    object WifiListScreen : Screen("WifiListScreen", R.string.wifi_list)
PIN 입력 화면과 WiFi 목록 화면을 추가했습니다.

2022-08-06 16:17 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +fun startScreenBtnClick(homeScreen: Screen.HomeScreen) {
이 부분에 문제가 있는데, 다른 파일들에선 문제가 없는 startScreenBtnClick이 WifiListScreen.kt에서는 `Unresolved reference: startScreenBtnClick` 라고 오류가 나서 일단 돌아가게 하려고 추가했습니다.
위의 문제가 해결되면 지우겠습니다!

2022-08-06 16:17 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/enter_PIN/ui/EnterPINScreen.kt
> +            onClick = { },
WiFi 비밀번호를 제공하는 페이지가 완성된 뒤 누르면 해당 페이지로 넘어가도록 추가 필요

2022-08-06 16:17 UTC, Kimhaedam commented on app/src/androidTest/java/com/euphony/waple/PinUnitTest.kt
> +    @Test
유닛테스트에 대해 공부하고 있는데 아직 이 부분 작성을 끝내지 못 했습니다 💧.. 
다른 유닛테스트들이 모두 `test/java/com/euphony/waple`에 있어서 나중에 그쪽으로 이동시킬까 하는데 괜찮을까요?
* (https://github.com/euphony-io/waple/tree/develop/app/src/test/java/com/euphony/waple)

2022-08-06 22:37 UTC, zion830 requested changes
해담님 여기서  .gradle 하위에 들어간 파일 전체 삭제가 필요할거 같습니다!
PR 열고나서 네번째 탭 file changed를 클릭해서 xml이나 kotlin, gradle 파일 등만 포함되어 있는지 한번 확인하면 좋을거같아요!

2022-08-06 22:39 UTC, zion830 commented on app/src/androidTest/java/com/euphony/waple/PinUnitTest.kt
> +    @Test
androidTest는 android에 종속성이 있는 부분(UI 테스트나 Context가 필요한 테스트)을 테스트할때 사용하는 폴더고, test는 일반적인 테스트를 작성하는 폴더예요. 그래서 Pin 같은 경우는 말씀 주신대로 test/java... 로 이동하는게 역할상 맞을 것 같습니다!

2022-08-06 22:40 UTC, zion830 commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +        )}}}}
이부분 }}}} 이렇게 되어있어서 어떤 블록이 종료되는 건지 구분하기가 조금 어려운거 같아요, 정렬 한번 해주시면 좋을거 같습니다!

2022-08-06 22:43 UTC, zion830 commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +fun startScreenBtnClick(homeScreen: Screen.HomeScreen) {
다른 화면들은 startScreenBtnClick라는 이름의 함수를 인자로 받고 있어서 그래요! 다른 화면들에서 navigation으로 화면 전환하는 코드를 참고해서 교체하면 해결될거 같아요 ㅎㅎ

2022-08-06 22:44 UTC, zion830 commented on app/src/main/java/com/euphony/waple/NavController.kt
> +                    EnterPINScreen("navController")
여기서 혹시 navController라는 문자열을 넘기는 이유가 뭘까요?!

2022-08-06 22:45 UTC, zion830 commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +                            }
여기도 괄호 위치 정렬 부탁드려용

2022-08-06 22:49 UTC, zion830 commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +fun startScreenBtnClick(homeScreen: Screen.HomeScreen) {
이 부분 고차함수로 한번 찾아보시면 좋을거같아욧 [블로그 글](https://medium.com/lucky-sonnie/kotlin-8%EC%9E%A5-%EA%B3%A0%EC%B0%A8%ED%95%A8%EC%88%98-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%EC%99%80-%EB%B0%98%ED%99%98-%EA%B0%92%EC%9C%BC%EB%A1%9C-%EB%9E%8C%EB%8B%A4-%EC%82%AC%EC%9A%A9-4d2e14870750)

2022-08-07 08:43 UTC, Kimhaedam commented on app/src/main/java/com/euphony/waple/wifi_list/ui/WifiListScreen.kt
> +fun startScreenBtnClick(homeScreen: Screen.HomeScreen) {
감사합니다!!✨

2022-08-10 10:09 UTC, closed without merging